name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build
        run: ./amper build

      - name: Test
        run: ./amper test
        
      - name: Test Results
        uses: test-summary/action@v2
        with:
          paths: "build/reports/TEST-*.xml"
